version: "3.7"

services:
  db:
    image: postgres:12.10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=arcade
      - POSTGRES_USER=arcade
      - POSTGRES_PASSWORD=d3m0
  mqtt-broker:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8081:8081"
      - "8083:8083"
      - "18083:18083"
    depends_on:
      - "db"
    environment:
      - "EMQX_LOADED_PLUGINS=emqx_auth_pgsql"
      - "EMQX_AUTH__PGSQL__SERVER=db:5432"
      - "EMQX_AUTH__PGSQL__USERNAME=arcade"
      - "EMQX_AUTH__PGSQL__PASSWORD=d3m0"
      - "EMQX_AUTH__PGSQL__DATABASE=main"
      - "EMQX_AUTH__PGSQL__ENCODING=utf-8"
      - "EMQX_AUTH__PGSQL__PASSWORD_HASH=pbkdf2,sha256,26000"
      - "EMQX_AUTH__PGSQL__AUTH_QUERY=select password_hash from \"user\" where username = '%u' limit 1"
      - "EMQX_AUTH__PGSQL__SUPER_QUERY=select is_superuser from \"user\" where username = '%u' limit 1"
      - "EMQX_AUTH__PGSQL__ACL_QUERY=select permission, action, topic FROM \"mqtt_acl\" WHERE username = '%u'"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SERVICES=lambda,s3
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
  localstack_data:
