"""empty message

Revision ID: 05dac3e3e19b
Revises: 7d0ec043e044
Create Date: 2023-01-29 16:35:42.570394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dac3e3e19b'
down_revision = '7d0ec043e044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('description', sa.String(), nullable=True))
    op.add_column('mqtt_acl', sa.Column('permission', sa.String(), nullable=True))
    op.add_column('mqtt_acl', sa.Column('action', sa.String(), nullable=True))
    op.drop_index('ix_mqtt_acl_clientid', table_name='mqtt_acl')
    op.drop_index('ix_mqtt_acl_ipaddr', table_name='mqtt_acl')
    op.drop_column('mqtt_acl', 'ipaddr')
    op.drop_column('mqtt_acl', 'access')
    op.drop_column('mqtt_acl', 'clientid')
    op.drop_column('mqtt_acl', 'allow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_acl', sa.Column('allow', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mqtt_acl', sa.Column('clientid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mqtt_acl', sa.Column('access', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mqtt_acl', sa.Column('ipaddr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_mqtt_acl_ipaddr', 'mqtt_acl', ['ipaddr'], unique=False)
    op.create_index('ix_mqtt_acl_clientid', 'mqtt_acl', ['clientid'], unique=False)
    op.drop_column('mqtt_acl', 'action')
    op.drop_column('mqtt_acl', 'permission')
    op.drop_column('feed', 'description')
    # ### end Alembic commands ###
