"""empty message

Revision ID: 244d8d2a6c72
Revises: b3c31f32e95a
Create Date: 2022-06-05 11:00:57.649284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244d8d2a6c72'
down_revision = 'b3c31f32e95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emqx_pwd', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'emqx_pwd')
    # ### end Alembic commands ###
