"""empty message

Revision ID: 9ee61a894a0f
Revises: 7a2fe92bb1f7
Create Date: 2022-08-01 09:14:27.702889

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9ee61a894a0f'
down_revision = '7a2fe92bb1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_user')
    op.add_column('device', sa.Column('key', sa.String(length=80), nullable=True))
    op.add_column('device', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'feed', ['feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'feed_id')
    op.drop_column('device', 'owner_id')
    op.drop_column('device', 'key')
    op.create_table('local_user',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('guid', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='local_user_pkey')
                    )
    # ### end Alembic commands ###
