"""empty message

Revision ID: 7d0ec043e044
Revises: ca3e3ceb1b31
Create Date: 2022-08-28 07:30:05.296554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0ec043e044'
down_revision = 'ca3e3ceb1b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'thumbnail')
    # ### end Alembic commands ###
