"""empty message

Revision ID: 9190a8965392
Revises: 9ee61a894a0f
Create Date: 2022-08-01 09:18:57.121393

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9190a8965392'
down_revision = '9ee61a894a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('bucket', sa.String(), nullable=True))
    op.add_column('game', sa.Column('version', sa.String(), nullable=True))
    op.drop_column('game', 'storage_slug')
    op.drop_column('game', 'played')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('played', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('storage_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('game', 'version')
    op.drop_column('game', 'bucket')
    # ### end Alembic commands ###
