# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "master", "add-ci-testing" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes: 
       - ${{ github.workspace }}./app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Docker
      run: |
        composer install
        docker-compose up
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==5.4.1
        pip install -r requirements.txt --force
        
    - name: Test with pytest
      working-directory: ./server
      run: pytest
